language: php

php:
  - 7.1
  - 7.2

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest --prefer-stable"
    - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer update --no-interaction --prefer-dist $COMPOSER_FLAGS

script:
  - vendor/bin/parallel-lint --exclude vendor .
  - vendor/bin/phpcs --standard=psr2 src tests
  - vendor/bin/phpstan analyse
  - vendor/bin/phpstan analyse -c phpstan.dev.neon.dist
  - vendor/bin/phpunit

after_script:
  - |
    if [[ "$TRAVIS_PHP_VERSION" != 'hhvm' && "$TRAVIS_PHP_VERSION" != '7.0' ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover build/clover.xml
    fi
